import type { GetStaticProps } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic'
import type { Post } from '../types/post'

const MapWithNoSSR = dynamic(() => import('../components/BikeMap/BikeMap'), {
  ssr: false,
})

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch('http://localhost:5000/api/posts')
  const posts: Post[] = await res.json()
  const postsPromises = posts.map(async (p) => {
    const res = await fetch('http://localhost:5000/api/posts/' + p.id)
    const post: Post = await res.json()
    return post
  })

  const fullPosts = await Promise.all(postsPromises)

  return {
    props: {
      posts: fullPosts,
    },
  }
}

type Props = {
  posts: Post[]
}

const Home = ({ posts }: Props) => {
  return (
    <div className={styles.root}>
      <Head>
        <title>riton bike adventure</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        ></link>
      </Head>

      <main className={styles.main}>
        <MapWithNoSSR posts={posts} />
      </main>

      <footer className={styles.footer}>🚴 riton bike adventure 🍃</footer>
    </div>
  )
}

export default Home
