import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic'

const MapWithNoSSR = dynamic(() => import('../components/BikeMap/BikeMap'), {
  ssr: false,
})

const Home: NextPage = () => {
  return (
    <div className={styles.root}>
      <Head>
        <title>riton bike adventure</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"></link>
      </Head>

      <main className={styles.main}>
        <MapWithNoSSR />
      </main>

      <footer className={styles.footer}>🚴 riton bike adventure 🍃</footer>
    </div>
  )
}

export default Home
